### ISSUE TITLE
flag label error

### ISSUE THREAD

**Issue by DrRob** [Aeprox/ESPLogger#7]
It's a tiny thing, but "TSL2561_GAIN_0X" should really be "TSL2561_GAIN_1X".

**Comment by Aeprox** [comment]
Thanks! You are correct.This is a left-over of the original library hamishcunningham/fishy-wifi@98fa06e8a39df02bccfa5ae4540c4e46e9175b63

Additionally, this made me realize these definitions are no longer used and can be removed to free another few bytes of memory.
